version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn test
      - echo "Creating .env file"
      - echo "MONGO_USERNAME=$MONGO_USERNAME\nMONGO_PASSWORD=$MONGO_PASSWORD\nGRAPHQL_API_URL=$GRAPHQL_API_URL\nGRAPHQL_API_KEY=$GRAPHQL_API_KEY\nONESIGNAL_API_KEY=$ONESIGNAL_API_KEY\nONESIGNAL_APP_ID=$ONESIGNAL_APP_ID" > .env
  build:
    commands:
      - echo Starting Deployment
      - npx sst deploy --stage $STAGE
  post_build:
    commands:
      - echo Build Completed on `date`
